server:
  port: 8000

spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/studentScoreManage?useUnicode=true&characterEncoding=utf-8&useSSL=true

graduate:
  password:
    key: 123456789

mybatis:
  mapper-locations: classpath*:mapper/*.xml
logging:
  config: classpath:logback-spring.xml